package main.functions;
/*
Consider the following algorithm
 Start with a positive number n
 if n is even then divide by 2
 if n is odd then multiply by 3 and add 1
 continue this until n becomes 1

The Guthrie sequence of a positive number n is defined to be
the numbers generated by the above algorithm.*/


public class IsGuthrieSequence {

    public static int isGuthrieSequence(int[] a)
    {
        if(a[a.length-1] != 1) return 0;

        for(int i = 0; i< a.length -1;i++)
        {
            //n is even then divide by 2
            if(a[i]%2 == 0){
                if(a[i]/2 != a[i+1])
                    return 0;

            }else
                if(a[i]*3 + 1 != a [i+1])
                    return 0;


        }
        return 1;
    }
}
